{
 "title": "Participant Hydra Nodes",
 "description": "Monitoring for participant's node. This dashboard contains metrics of the hydra nodes and also of the system resources.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"hydra_nodes\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Peer connected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(hydra_head_peers_connected{instance=~\"${instance:raw}\"}, \"host\", \"$1\", \"instance\", \"^([^.]*).*\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hydra Head Confirmed Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hydra_head_confirmed_tx{instance=~\"${instance:raw}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hydra Head Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "hydra_head_inputs{instance=~\"${instance:raw}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hydra Head Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "hydra_head_requested_tx{instance=~\"${instance:raw}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hydra Head Tx Confirmation Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "hydra_head_tx_confirmation_time_ms_sum{instance=~\"${instance:raw}\"} / hydra_head_tx_confirmation_time_ms_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"hydra_nodes\", instance=~\"${instance:raw}\"} == 1)"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 - (sum(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"${instance:raw}\"}[5m])) * 100 / sum(rate(node_cpu_seconds_total{instance=~\"${instance:raw}\"}[5m])))"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"${instance:raw}\"} - node_memory_MemAvailable_bytes{instance=~\"${instance:raw}\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"${instance:raw}\"}[1m])) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"${instance:raw}\"} - node_memory_MemAvailable_bytes{instance=~\"${instance:raw}\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",instance=~\"${instance:raw}\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"${instance:raw}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hydra persistence folder size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "folder_size_bytes{instance=~\"${instance:raw}\"}",
     "legendFormat": "{{instance}} {{folder}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\",instance=~\"${instance:raw}\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\",instance=~\"${instance:raw}\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}