version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - .:/data
      - ./mainnet:/mainnet
    working_dir: /data
    environment:
      - CARDANO_SOCKET_PATH=/mainnet/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/mainnet/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/mainnet/cardano-node/config.json"
      , "--topology", "/mainnet/cardano-node/topology.json"
      , "--database-path", "/mainnet/db"
      ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
