#!/usr/bin/env bash

set -euo pipefail

main() {
  gh extension install --force actions/gh-actions-cache

  local repo="$GITHUB_REPOSITORY"
  local branch="$GITHUB_REF"
  local prefix="${PREFIX:-}" 

  list_caches $repo $branch "${prefix}dist" \
  | all_but_the_first_one \
  | delete_cache $branch $repo
}

list_caches() {
  local repo="$1"
  local branch="$2"
  local cache="$3"
  gh actions-cache list -R "$repo" -B "$branch" --key "$cache" --order desc | cut -f 1
}

all_but_the_first_one() {
  sed 1d
}

delete_cache() {
  local repo="$1"
  local branch="$2"

  while read cache
  do
    gh actions-cache delete "$cache" -R "$repo" -B "$branch" --confirm
  done
}

main "$@"