#!/usr/bin/env bash

set -euxo pipefail

mkdir -p src
mkdir -p srv/bin
# Install libsodium
# Using revision from https://github.com/input-output-hk/iohk-nix
(
  cd src
  git clone https://github.com/input-output-hk/libsodium
  cd libsodium
  git checkout dbb48cce5429cb6585c9034f002568964f1ce567
  ./autogen.sh
  ./configure --prefix="$(realpath $PWD/../../srv)"
  make
  make install
)

# Install secp256k1
# Using revision from https://github.com/input-output-hk/iohk-nix
(
  cd src
  git clone https://github.com/bitcoin-core/secp256k1
  cd secp256k1
  git checkout v0.3.2
  ./autogen.sh
  ./configure --enable-module-schnorrsig --enable-experimental --prefix="$(realpath $PWD/../../srv)"
  make
  make install
)

# Install cardano-node
curl -L https://github.com/input-output-hk/cardano-node/releases/download/8.1.2/cardano-node-8.1.2-linux.tar.gz -o src/cardano-node.tar.gz
tar xfz src/cardano-node.tar.gz -C srv/bin

cat <<EOF
# Setup the following environment variables:
LD_LIBRARY_PATH="$(realpath $PWD/srv)/lib:${LD_LIBRARY_PATH:-}"
PKG_CONFIG_PATH="$(realpath $PWD/srv)/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
PATH="$(realpath $PWD/srv)/bin:${PATH:-}
EOF
