#!/usr/bin/env bash

set -euxo pipefail

sudo apt-get install -y --no-install-recommends \
  `# Install netbase to work around https://github.com/input-output-hk/cardano-node/issues/2752A` \
  netbase \
  `# Install ghcup dependencies` \
  curl \
  libnuma-dev \
  zlib1g-dev \
  libgmp-dev \
  libgmp10 \
  git \
  wget \
  lsb-release \
  software-properties-common \
  gnupg2 \
  apt-transport-https \
  gcc \
  autoconf \
  automake \
  build-essential \
  `# Install cardano-node dependencies see https://developers.cardano.org/docs/get-started/installing-cardano-node/#linux` \
  automake \
  build-essential \
  pkg-config \
  libffi-dev \
  libgmp-dev \
  libssl-dev \
  libtinfo-dev \
  libsystemd-dev \
  zlib1g-dev \
  make \
  g++ \
  tmux \
  git \
  jq \
  wget \
  libncursesw5 \
  libtool \
  autoconf

# Needed to validate Hydra json schemas
pip install check-jsonschema

# Install ghc and cabal
version_ghc=${VERSION_GHC:-8.10.7}
ghcup install ghc ${version_ghc}
ghcup set ghc ${version_ghc}