title: "Hydra HeadV1 Specification: Coordinated Head protocol"
subtitle: DRAFT
classoption:
  - 11pt
documentclass: article
author: "Sebastian Nagel sebastian.nagel@iohk.io"
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
numbersections: true
boxlinks: true

# TODO: fix bibliography in html output
suppress-bibliography: true

bibliography: short.bib
reference-section-title: References
link-bibliography: true
link-citations: true
csl: elsevier-with-titles.csl

# TODO: use a sane geometry, this is currently replicating the tex source
geometry: "left=1in, right=1in"
