{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.8";
      identifier = { name = "gray-code"; version = "0.3.1"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "s.astanin@gmail.com";
      author = "Sergey Astanin";
      homepage = "http://bitbucket.org/astanin/hs-gray-code";
      url = "";
      synopsis = "Gray code encoder/decoder.";
      description = "Gray code is a binary numeral system where two successive numbers\ndiffer in only one bit.\n\nThis package allows to convert numbers to one of the possible Gray\ncodes and back. Two binary representations of a number are supported:\n@[Bool]@ and types of @FiniteBits@ type class.\n@FiniteBits@ is the default implementation.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [ (hsPkgs."base" or (errorHandler.buildDepError "base")) ];
        buildable = true;
        };
      tests = {
        "test-qc" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."QuickCheck" or (errorHandler.buildDepError "QuickCheck"))
            ];
          buildable = true;
          };
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/gray-code-0.3.1.tar.gz";
      sha256 = "5b0d04f6fe4c90157d669119c39da6d349a06eca3a7a834b7a5dcb5e89a8172c";
      });
    }) // {
    package-description-override = "-- gray-code.cabal auto-generated by cabal init. For additional\n-- options, see\n-- http://www.haskell.org/cabal/release/cabal-latest/doc/users-guide/authors.html#pkg-descr.\n-- The name of the package.\nName:                gray-code\n\n-- The package version. See the Haskell package versioning policy\n-- (http://www.haskell.org/haskellwiki/Package_versioning_policy) for\n-- standards guiding when and how versions should be incremented.\nVersion:             0.3.1\n\n-- A short (one-line) description of the package.\nSynopsis:            Gray code encoder/decoder.\n\n-- A longer description of the package.\nDescription:\n   Gray code is a binary numeral system where two successive numbers\n   differ in only one bit.\n   .\n   This package allows to convert numbers to one of the possible Gray\n   codes and back. Two binary representations of a number are supported:\n   @[Bool]@ and types of @FiniteBits@ type class.\n   @FiniteBits@ is the default implementation.\n\n-- URL for the project homepage or repository.\nHomepage:            http://bitbucket.org/astanin/hs-gray-code\n\n-- The license under which the package is released.\nLicense:             BSD3\n\n-- The file containing the license text.\nLicense-file:        LICENSE\n\n-- The package author(s).\nAuthor:              Sergey Astanin\n\n-- An email address to which users can send suggestions, bug reports,\n-- and patches.\nMaintainer:          s.astanin@gmail.com\n\n-- A copyright notice.\n-- Copyright:\n\n-- Stability of the pakcage (experimental, provisional, stable...)\nStability:           Experimental\n\nCategory:            Codec\n\nBuild-type:          Simple\n\n-- Extra files to be distributed with the package, such as examples or\n-- a README.\nExtra-source-files:\n     Codec/Binary/Gray_props.hs\n\nExtra-doc-files:\n     CHANGELOG\n\n-- Constraint on the version of Cabal needed to build this package.\nCabal-version:       >=1.8\n\n\nLibrary\n  -- Modules exported by the library.\n  Exposed-modules:\n     Codec.Binary.Gray\n     , Codec.Binary.Gray.Bits\n     , Codec.Binary.Gray.List\n\n  -- Packages needed in order to build this package.\n  Build-depends:\n     base >= 4.7 && < 5\n\n  -- Modules not exported by this package.\n  -- Other-modules:\n\n  -- Extra tools (e.g. alex, hsc2hs, ...) needed to build the source.\n  -- Build-tools:\n\nTest-Suite test-qc\n    type:       exitcode-stdio-1.0\n    main-is:    test.hs\n    build-depends: base, QuickCheck >= 2";
    }