{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.8";
      identifier = { name = "matrix"; version = "0.3.6.1"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "Daniel Díaz (dhelta `dot` diaz `at` gmail `dot` com)";
      author = "Daniel Díaz";
      homepage = "";
      url = "";
      synopsis = "A native implementation of matrix operations.";
      description = "Matrix library. Basic operations and some algorithms.\n\nTo get the library update your cabal package list (if needed) with @cabal update@ and\nthen use @cabal install matrix@, assuming that you already have Cabal installed.\nUsage examples are included in the API reference generated by Haddock.\n\nIf you want to use GSL, BLAS and LAPACK, @hmatrix@ (<http://hackage.haskell.org/package/hmatrix>)\nis the way to go.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
          (hsPkgs."deepseq" or (errorHandler.buildDepError "deepseq"))
          (hsPkgs."primitive" or (errorHandler.buildDepError "primitive"))
          (hsPkgs."semigroups" or (errorHandler.buildDepError "semigroups"))
          (hsPkgs."loop" or (errorHandler.buildDepError "loop"))
          ];
        buildable = true;
        };
      tests = {
        "matrix-test" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."matrix" or (errorHandler.buildDepError "matrix"))
            (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
            (hsPkgs."QuickCheck" or (errorHandler.buildDepError "QuickCheck"))
            (hsPkgs."tasty-quickcheck" or (errorHandler.buildDepError "tasty-quickcheck"))
            ];
          buildable = true;
          };
        "matrix-examples" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."matrix" or (errorHandler.buildDepError "matrix"))
            ];
          buildable = true;
          };
        };
      benchmarks = {
        "matrix-mult" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."matrix" or (errorHandler.buildDepError "matrix"))
            (hsPkgs."criterion" or (errorHandler.buildDepError "criterion"))
            ];
          buildable = true;
          };
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/matrix-0.3.6.1.tar.gz";
      sha256 = "fa976ca3bc98149ce59b7ae37869eda615562711e1fef90889f6e0c4f2093b2c";
      });
    }) // {
    package-description-override = "Name: matrix\r\nVersion: 0.3.6.1\r\nx-revision: 1\r\nAuthor: Daniel Díaz\r\nCategory: Math\r\nBuild-type: Simple\r\nLicense: BSD3\r\nLicense-file: license\r\nMaintainer: Daniel Díaz (dhelta `dot` diaz `at` gmail `dot` com)\r\nStability: In development\r\nBug-reports: https://github.com/Daniel-Diaz/matrix/issues\r\nSynopsis: A native implementation of matrix operations.\r\nDescription:\r\n  Matrix library. Basic operations and some algorithms.\r\n  .\r\n  To get the library update your cabal package list (if needed) with @cabal update@ and\r\n  then use @cabal install matrix@, assuming that you already have Cabal installed.\r\n  Usage examples are included in the API reference generated by Haddock.\r\n  .\r\n  If you want to use GSL, BLAS and LAPACK, @hmatrix@ (<http://hackage.haskell.org/package/hmatrix>)\r\n  is the way to go.\r\nCabal-version: >= 1.8\r\nExtra-source-files:\r\n  readme.md\r\n  -- Benchmarks\r\n  bench/mult.hs\r\n\r\nSource-repository head\r\n  type: git\r\n  location: git://github.com/Daniel-Diaz/matrix.git\r\n\r\nLibrary\r\n  Build-depends: base >= 4.8 && < 5\r\n               , vector >= 0.10\r\n               , deepseq >= 1.3.0.0 && < 1.5\r\n               , primitive >= 0.5\r\n               , semigroups >= 0.9\r\n               , loop >= 0.2\r\n  Exposed-modules: Data.Matrix\r\n  GHC-Options: -Wall -O2 -fstatic-argument-transformation\r\n\r\nBenchmark matrix-mult\r\n  type: exitcode-stdio-1.0\r\n  hs-source-dirs: bench\r\n  main-is: mult.hs\r\n  build-depends: base == 4.*\r\n               , matrix\r\n               , criterion\r\n  ghc-options: -O2 -fstatic-argument-transformation\r\n\r\nTest-Suite matrix-test\r\n  type: exitcode-stdio-1.0\r\n  hs-source-dirs: test\r\n  main-is: Main.hs\r\n  build-depends: base == 4.*\r\n               , matrix\r\n               , tasty\r\n               , QuickCheck\r\n               , tasty-quickcheck\r\n\r\nTest-Suite matrix-examples\r\n  type: exitcode-stdio-1.0\r\n  hs-source-dirs: test\r\n  main-is: Examples.hs\r\n  build-depends: base == 4.*\r\n               , matrix\r\n";
    }