{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "microlens-th"; version = "0.4.3.10"; };
      license = "BSD-3-Clause";
      copyright = "";
      maintainer = "Steven Fontanella <steven.fontanella@gmail.com>";
      author = "Eric Mertens, Edward Kmett, Artyom Kazak";
      homepage = "http://github.com/monadfix/microlens";
      url = "";
      synopsis = "Automatic generation of record lenses for microlens";
      description = "This package lets you automatically generate lenses for data types; code was extracted from the lens package, and therefore generated lenses are fully compatible with ones generated by lens (and can be used both from lens and microlens).\n\nThis package is a part of the <http://hackage.haskell.org/package/microlens microlens> family; see the readme <https://github.com/monadfix/microlens#readme on Github>.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."microlens" or (errorHandler.buildDepError "microlens"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."transformers" or (errorHandler.buildDepError "transformers"))
          (hsPkgs."template-haskell" or (errorHandler.buildDepError "template-haskell"))
          (hsPkgs."th-abstraction" or (errorHandler.buildDepError "th-abstraction"))
          ];
        buildable = true;
        };
      tests = {
        "templates" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."microlens" or (errorHandler.buildDepError "microlens"))
            (hsPkgs."microlens-th" or (errorHandler.buildDepError "microlens-th"))
            (hsPkgs."tagged" or (errorHandler.buildDepError "tagged"))
            ];
          buildable = true;
          };
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/microlens-th-0.4.3.10.tar.gz";
      sha256 = "2c50100235949c00defcdb8c01d8eb5e2e45e524a9b552d3c0c8bb8224ece2b5";
      });
    }) // {
    package-description-override = "name:                microlens-th\nversion:             0.4.3.10\nx-revision: 1\nsynopsis:            Automatic generation of record lenses for microlens\ndescription:\n  This package lets you automatically generate lenses for data types; code was extracted from the lens package, and therefore generated lenses are fully compatible with ones generated by lens (and can be used both from lens and microlens).\n  .\n  This package is a part of the <http://hackage.haskell.org/package/microlens microlens> family; see the readme <https://github.com/monadfix/microlens#readme on Github>.\nlicense:             BSD3\nlicense-file:        LICENSE\nauthor:              Eric Mertens, Edward Kmett, Artyom Kazak\nmaintainer:          Steven Fontanella <steven.fontanella@gmail.com>\nhomepage:            http://github.com/monadfix/microlens\nbug-reports:         http://github.com/monadfix/microlens/issues\ncategory:            Data, Lenses\nbuild-type:          Simple\nextra-source-files:\n  CHANGELOG.md\ncabal-version:       >=1.10\ntested-with:         GHC==7.6.3\n                     GHC==7.8.4\n                     GHC==7.10.3\n                     GHC==8.0.2\n                     GHC==8.2.2\n                     GHC==8.4.4\n                     GHC==8.6.5\n                     GHC==8.8.4\n                     GHC==8.10.7\n                     GHC==9.0.2\n                     GHC==9.2.4\n                     GHC==9.4.1\n\nsource-repository head\n  type:                git\n  location:            git://github.com/monadfix/microlens.git\n\nlibrary\n  exposed-modules:     Lens.Micro.TH\n                       Lens.Micro.TH.Internal\n  -- other-modules:\n  -- other-extensions:\n  build-depends:       base >=4.5 && <5\n                     , microlens >=0.4.0 && <0.5\n                     , containers >=0.5 && <0.7\n                     , transformers\n                     , template-haskell >=2.8 && <2.20\n                     , th-abstraction >=0.4.1 && <0.5\n\n  ghc-options:\n    -Wall -fwarn-tabs\n    -O2 -fdicts-cheap -funbox-strict-fields\n    -fmax-simplifier-iterations=10\n\n  hs-source-dirs:      src\n  default-language:    Haskell2010\n\ntest-suite templates\n  type: exitcode-stdio-1.0\n  main-is: templates.hs\n  other-modules: T799 T917 T972\n  ghc-options: -Wall -threaded\n  hs-source-dirs: test\n\n  build-depends: base, microlens, microlens-th, tagged\n\n  default-language: Haskell2010\n";
    }