{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "tasty-quickcheck"; version = "0.10.2"; };
      license = "MIT";
      copyright = "";
      maintainer = "Roman Cheplyaka <roma@ro-che.info>";
      author = "Roman Cheplyaka <roma@ro-che.info>";
      homepage = "https://github.com/UnkindPartition/tasty";
      url = "";
      synopsis = "QuickCheck support for the Tasty test framework.";
      description = "QuickCheck support for the Tasty test framework.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."tagged" or (errorHandler.buildDepError "tagged"))
          (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
          (hsPkgs."random" or (errorHandler.buildDepError "random"))
          (hsPkgs."QuickCheck" or (errorHandler.buildDepError "QuickCheck"))
          (hsPkgs."optparse-applicative" or (errorHandler.buildDepError "optparse-applicative"))
          ];
        buildable = true;
        };
      tests = {
        "test" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
            (hsPkgs."tasty-quickcheck" or (errorHandler.buildDepError "tasty-quickcheck"))
            (hsPkgs."tasty-hunit" or (errorHandler.buildDepError "tasty-hunit"))
            (hsPkgs."pcre-light" or (errorHandler.buildDepError "pcre-light"))
            ];
          buildable = if !(compiler.isGhc && (compiler.version).ge "8.0") || system.isWindows
            then false
            else true;
          };
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/tasty-quickcheck-0.10.2.tar.gz";
      sha256 = "b4884c815db26a543ee1062664ee051ac89d51b2c2526d30029c6eb95b36cce2";
      });
    }) // {
    package-description-override = "-- Initial tasty-quickcheck.cabal generated by cabal init.  For further\n-- documentation, see http://haskell.org/cabal/users-guide/\n\nname:                tasty-quickcheck\nversion:             0.10.2\nsynopsis:            QuickCheck support for the Tasty test framework.\ndescription:         QuickCheck support for the Tasty test framework.\nlicense:             MIT\nlicense-file:        LICENSE\nauthor:              Roman Cheplyaka <roma@ro-che.info>\nmaintainer:          Roman Cheplyaka <roma@ro-che.info>\n-- copyright:\nhomepage:            https://github.com/UnkindPartition/tasty\nbug-reports:         https://github.com/UnkindPartition/tasty/issues\ncategory:            Testing\nbuild-type:          Simple\nextra-source-files:  CHANGELOG.md\ncabal-version:       >=1.10\n\nSource-repository head\n  type:     git\n  location: git://github.com/UnkindPartition/tasty.git\n  subdir:   quickcheck\n\nlibrary\n  exposed-modules:     Test.Tasty.QuickCheck\n  -- other-modules:\n  other-extensions:    GeneralizedNewtypeDeriving, DeriveDataTypeable\n  build-depends:       base >= 4.8 && < 5, tagged, tasty >= 1.0.1, random, QuickCheck >= 2.10,\n                       optparse-applicative\n\n  -- hs-source-dirs:\n  default-language:    Haskell2010\n  default-extensions: CPP\n  ghc-options: -Wall\n\ntest-suite test\n  default-language:\n    Haskell2010\n  default-extensions: CPP\n  type:\n    exitcode-stdio-1.0\n  hs-source-dirs:\n    tests\n  main-is:\n    test.hs\n  build-depends:\n      base >= 4.7 && < 5\n    , tasty\n    , tasty-quickcheck\n    , tasty-hunit\n    , pcre-light\n  ghc-options: -Wall\n  if (!impl(ghc >= 8.0) || os(windows))\n    buildable: False\n";
    }