{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "tasty-hunit"; version = "0.10.0.3"; };
      license = "MIT";
      copyright = "";
      maintainer = "Roman Cheplyaka <roma@ro-che.info>";
      author = "Roman Cheplyaka <roma@ro-che.info>";
      homepage = "https://github.com/feuerbach/tasty";
      url = "";
      synopsis = "HUnit support for the Tasty test framework.";
      description = "HUnit support for the Tasty test framework.\n\nNote that this package does not depend on HUnit but\nimplements the relevant subset of its API. The name is a\nlegacy of the early versions of tasty-hunit and of\ntest-framework-hunit, which did depend on HUnit.";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
          ] ++ (pkgs.lib).optional (compiler.isGhc && (compiler.version).ge "7.4") (hsPkgs."call-stack" or (errorHandler.buildDepError "call-stack"));
        buildable = true;
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/tasty-hunit-0.10.0.3.tar.gz";
      sha256 = "b7ef1912ece25b9396d2c69c31e63f82facc95edac8fc1abbf84e8c3c7ffe63f";
      });
    }) // {
    package-description-override = "-- Initial tasty-hunit.cabal generated by cabal init.  For further\n-- documentation, see http://haskell.org/cabal/users-guide/\n\nname:                tasty-hunit\nversion:             0.10.0.3\nsynopsis:            HUnit support for the Tasty test framework.\ndescription:         HUnit support for the Tasty test framework.\n                     .\n                     Note that this package does not depend on HUnit but\n                     implements the relevant subset of its API. The name is a\n                     legacy of the early versions of tasty-hunit and of\n                     test-framework-hunit, which did depend on HUnit.\nlicense:             MIT\nlicense-file:        LICENSE\nauthor:              Roman Cheplyaka <roma@ro-che.info>\nmaintainer:          Roman Cheplyaka <roma@ro-che.info>\nhomepage:            https://github.com/feuerbach/tasty\nbug-reports:         https://github.com/feuerbach/tasty/issues\n-- copyright:\ncategory:            Testing\nbuild-type:          Simple\nextra-source-files:  CHANGELOG.md\ncabal-version:       >=1.10\n\nSource-repository head\n  type:     git\n  location: git://github.com/feuerbach/tasty.git\n  subdir:   hunit\n\nlibrary\n  exposed-modules:     Test.Tasty.HUnit\n  other-modules:       Test.Tasty.HUnit.Orig\n                       Test.Tasty.HUnit.Steps\n  other-extensions:    TypeFamilies, DeriveDataTypeable\n  build-depends:       base >= 4.3 && < 5, tasty >= 1.2.2\n  if impl(ghc >= 7.4)\n    build-depends: call-stack\n  -- hs-source-dirs:\n  default-language:    Haskell2010\n  ghc-options: -Wall\n";
    }