{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "testing-type-modifiers"; version = "0.1.0.1"; };
      license = "LicenseRef-PublicDomain";
      copyright = "";
      maintainer = "jonas.duregard@gmail.com";
      author = "Jonas Duregård";
      homepage = "";
      url = "";
      synopsis = "Data type modifiers for property based testing";
      description = "Property based testing libraries such as QuickCheck tend to include type modifiers. Most of them\nare used to quantify over subsets of a type. For example a property on non-empty lists:\n\n@  prop_tail_length (NonEmpty xs) = length (tail xs) == length xs - 1 @\n\nThis library is intended to supply these modifiers to be used by testing libraries, in an effort to make\nproperties more portable between testing frameworks.\n\nFor every modifier it also provides an access function that converts to the underlying type, which\nenables point-free style properties as such:\n\n@\nprop_tail_length2 = (> 0) . length . nonEmpty\n@";
      buildType = "Simple";
      };
    components = {
      "library" = {
        depends = [ (hsPkgs."base" or (errorHandler.buildDepError "base")) ];
        buildable = true;
        };
      };
    } // {
    src = (pkgs.lib).mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/testing-type-modifiers-0.1.0.1.tar.gz";
      sha256 = "050bdade2c6f0122b1a04a3833ab7eea2399ffda8258bca6d93ba6614bb202f2";
      });
    }) // {
    package-description-override = "-- Initial testing-type-modifiers.cabal generated by cabal init.  For \r\n-- further documentation, see http://haskell.org/cabal/users-guide/\r\n\r\nname:                testing-type-modifiers\r\nversion:             0.1.0.1\r\nsynopsis:            Data type modifiers for property based testing\r\ndescription:         Property based testing libraries such as QuickCheck tend to include type modifiers. Most of them \r\n                     are used to quantify over subsets of a type. For example a property on non-empty lists:\r\n                     .\r\n                     @  prop_tail_length (NonEmpty xs) = length (tail xs) == length xs - 1 @\r\n                     .\r\n                     This library is intended to supply these modifiers to be used by testing libraries, in an effort to make  \r\n                     properties more portable between testing frameworks.\r\n                     .\r\n                     For every modifier it also provides an access function that converts to the underlying type, which \r\n                     enables point-free style properties as such: \r\n                     .\r\n                     @ \r\n                       prop_tail_length2 = (> 0) . length . nonEmpty \r\n                     @\r\n                     \r\n                     \r\nlicense:             PublicDomain\r\nlicense-file:        LICENSE\r\nauthor:              Jonas Duregård\r\nmaintainer:          jonas.duregard@gmail.com\r\n-- copyright:           \r\ncategory:            Testing\r\nbuild-type:          Simple\r\n-- extra-source-files:  \r\ncabal-version:       >=1.10\r\n\r\n\r\nsource-repository head   \r\n  type:      git\r\n  location:  https://github.com/JonasDuregard/testing-type-modifiers\r\n\r\nlibrary\r\n  exposed-modules:     Data.Modifiers\r\n  -- other-modules:       \r\n  other-extensions:    DeriveDataTypeable\r\n  build-depends:       base >=4 && <5\r\n  -- hs-source-dirs:      \r\n  default-language:    Haskell2010";
    }