x-cardano-node: &cardano-node
  image: ghcr.io/intersectmbo/cardano-node:latest
  environment:
    CARDANO_BLOCK_PRODUCER: true
  command: >
    run --topology /configs/configs/topology.json
      --config /configs/configs/config.json
      --database-path /state
      --socket-path /state/node.socket
      --tracer-socket-path-connect /tracer/tracer.socket
      --shelley-operational-certificate /configs/keys/opcert.cert
      --shelley-kes-key /configs/keys/kes.skey
      --shelley-vrf-key /configs/keys/vrf.skey
      --port 3001
      --host-addr 0.0.0.0
      +RTS -N -A16m -qg -qb -RTS
  restart:
    always
  depends_on:
      configurator:
        condition: service_completed_successfully

services:
  configurator:
    image: ghcr.io/cardano-foundation/antithesis/configurator:latest
    container_name: configurator
    volumes:
      - ./testnet.yaml:/testnet.yaml #  source of configurations
      - p1-configs:/configs/1 # configs for p1
      - p2-configs:/configs/2 # configs for p2
      - p3-configs:/configs/3 # configs for p3
      - p4-configs:/configs/4 # configs for p4
      - p5-configs:/configs/5 # configs for p5

  tracer:
    image: ghcr.io/cardano-foundation/antithesis/tracer:latest
    hostname: tracer.example
    container_name: tracer
    volumes:
      - tracer:/opt/cardano-tracer
    command:
       - "--config"
       - "tracer-config.yaml"

  p1:
    <<: *cardano-node
    container_name: p1
    hostname: p1.example
    volumes:
      - p1-configs:/configs
      - p1-state:/state
      - tracer:/tracer
  p2:
    <<: *cardano-node
    container_name: p2
    hostname: p2.example
    volumes:
      - p2-configs:/configs
      - tracer:/tracer
  p3:
    <<: *cardano-node
    container_name: p3
    hostname: p3.example
    volumes:
      - p3-configs:/configs
      - tracer:/tracer

  p4:
    <<: *cardano-node
    container_name: p4
    hostname: p4.example
    volumes:
      - p4-configs:/configs
      - tracer:/tracer

  p5:
    <<: *cardano-node
    container_name: p5
    hostname: p5.example
    volumes:
      - p5-configs:/configs
      - tracer:/tracer

  sidecar:
    image: ghcr.io/cardano-foundation/antithesis/sidecar:latest
    container_name: sidecar
    hostname: sidecar.example
    environment:
      POOLS: "5" # FIXME: could remove

  tracer-sidecar:
    image: ghcr.io/cardano-foundation/antithesis/tracer-sidecar:latest
    container_name: tracer-sidecar
    hostname: tracer-sidecar.example
    environment:
      POOLS: "5"
    volumes:
      - tracer:/opt/cardano-tracer

  hydra-setup:
    # TODO: implement
    image: ghcr.io/cardano-scaling/hydra-setup:latest
    environment:
      - ACTORS="alice,bob,carol"
      - CARDANO_NODE_SOCKET_PATH=/devnet/node.socket
      - CARDANO_NODE_NETWORK_ID=42
      - SEED_NETWORK=true
    volumes:
      - h1-setup:/setup
      - p1-state:/devnet
    depends_on:
      - p1

  h1:
    # XXX: 0.22.4 + --hydra-scripts-tx-id from file
    image: ghcr.io/cardano-scaling/hydra-node:antithesis
    depends_on:
      hydra-setup:
        condition: service_completed_successfully
    volumes:
      - h1-setup:/setup:ro
      - p1-state:/devnet
    hostname: h1.example
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--listen", "h1.example:5001"
      , "--monitoring-port", "6001"
      # , "--peer", "172.16.238.20:5001"
      # , "--peer", "172.16.238.30:5001"
      # TODO: implement
      , "--hydra-scripts-tx-id", "/setup/hydra-scripts.txid"
      , "--hydra-signing-key", "/setup/alice-hydra.sk"
      # , "--hydra-verification-key", "/keys/bob.vk"
      # , "--hydra-verification-key", "/keys/carol.vk"
      , "--cardano-signing-key", "/setup/alice-hydra.sk"
      # , "--cardano-verification-key", "/devnet/credentials/bob.vk"
      # , "--cardano-verification-key", "/devnet/credentials/carol.vk"
      , "--ledger-protocol-parameters", "/setup/protocol-parameters.json"
      , "--testnet-magic", "42"
      , "--node-socket", "/devnet/node.socket"
      , "--persistence-dir", "/state/persistence/alice"
      , "--contestation-period", "3s"
      ]
    restart: always

volumes:
  tracer:
  h1-setup:
  p1-state:
  p1-configs:
  p2-configs:
  p3-configs:
  p4-configs:
  p5-configs:

networks:
  default:
    name: cardano-node-testnet
    driver: bridge
    internal: ${INTERNAL_NETWORK}
