@startuml
queue EventQ as eq
database State as db
eq -> Node : nextEvent
Node -> db : getState
db --> Node : state: HeadState
Node -> HeadLogic: update(state)
HeadLogic --> Node : [st:StateEffect, ot:OtherEffect]
Node -> db: handle(st)
db -> db: persist(st)
db --> Node: ok
Other \\- Node : handle(ot)
@enduml
