node-id: "1-mirror"
listen: "127.0.0.1:5004"
advertise: "127.0.0.1:5004"
api-port: 4004
monitoring-port: 6004
hydra-signing-key: "demo/alice.sk"
peers:
  - address: "127.0.0.1:5001"
  - address: "127.0.0.1:5002"
    hydra-verification-key: "demo/bob.vk"
    cardano-verification-key: "hydra-cluster/config/credentials/bob.vk"
  - address: "127.0.0.1:5003"
    hydra-verification-key: "demo/carol.vk"
    cardano-verification-key: "hydra-cluster/config/credentials/carol.vk"
ledger-protocol-parameters: "devnet/protocol-parameters.json"
persistence-dir: "devnet/persistence/alice-mirror"
chain:
  mode: cardano
  cardano-signing-key: "hydra-cluster/config/credentials/alice.sk"
  contestation-period: 3
  deposit-period: 10
  backend:
    mode: direct
    testnet-magic: 42
    node-socket: "devnet/node.socket"
