name: Cachix push

on:
  pull_request:

jobs:
  cachix:
    name: Cachix push
    runs-on: [self-hosted, nixos]
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: 📐 Cachix push
      run: |
        export CACHIX_AUTH_TOKEN="${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}"
        nix run .#cachix-push
