name: "Test"

on:
  push:
    branches:
    - pepe

jobs:
  test:
    name: "Pepe"
    runs-on: ubuntu-latest
  
    steps:
    - name: 📥 Checkout repository to latest master
      uses: actions/checkout@v3
      with:
        repository: input-output-hk/hydra
        token: ${{ secrets.MY_TOKEN || github.token }}
        # Also ensure we have all history with all tags
        fetch-depth: 0
        
    - name: Get tag name
      id: latest_tag
      run: |
        echo "RELEASE_VERSION=$(echo $(git describe --abbrev=0 --tags))" >> $GITHUB_OUTPUT

    - name: 📥 Checkout repository to latest released version
      uses: actions/checkout@v3
      with:
        repository: input-output-hk/hydra
        token: ${{ secrets.MY_TOKEN || github.token }}
        # Also ensure we have all history with all tags
        fetch-depth: 0
        ref: ${{ steps.latest_tag.outputs.RELEASE_VERSION }}
