name: Setup Nix & Cachix
description: Installs nix and cachix with config values

inputs:
  authToken:
    required: true

runs:
  using: composite

  steps:
  - name: 🧹 Free disk space
    if: runner.os == 'Linux'
    shell: bash
    run: |
      echo "Disk space before cleanup:"
      df -h /
      # Remove unnecessary tools to free up disk space
      sudo rm -rf /usr/share/dotnet
      sudo rm -rf /usr/local/lib/android
      sudo rm -rf /opt/ghc
      sudo rm -rf /opt/hostedtoolcache/CodeQL
      sudo docker image prune --all --force || true
      echo "Disk space after cleanup:"
      df -h /

  - name: ❄ Prepare nix
    uses: cachix/install-nix-action@v30
    with:
      extra_nix_config: |
        accept-flake-config = true
        log-lines = 1000

  - name: ❄ Cachix cache of nix derivations
    uses: cachix/cachix-action@v15
    with:
      name: cardano-scaling
      authToken: '${{ inputs.authToken }}'
